services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
      - /app/node_modules