services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5000:5000"
    command: sh -c "npm ci --cache /tmp/.npm --include=dev && npm run dev --workspace=frontend"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app